### ISSUE TITLE
Not compatible with Versa 2?

### ISSUE THREAD

**Issue by PatrickF1** [mdmedley/cadence-coach#2]
Hi, thank you for developing this lovely app. Unfortunately, I won the Versa 2 and it looks like it's not compatible because the instructions say to use the physical buttons on the side of the tracker...but the Versa 2 only has one button, and it turns off the screen. I installed it anyway and confirmed I have no way of adjusting the cadence through the screen. Would it be possible to add compatibility with the 2? Thank you!

**Comment by mdmedley** [comment]
@patrickf3139 You are correct the app was designed before the Versa 2 was on the market but I will look into modifying the code to make it compatible with the Versa 2!

**Comment by PatrickF1** [comment]
Woohoo thank you!

**Comment by mdmedley** [comment]
@patrickf3139 I have made the changes to allow the target cadence to be adjusted using the touch screen. Tapping the upper half of the screen will increase the target cadence while tapping the lower half of the screen will lower the target cadence. I've submitted the new app to Fitbit for review. I will close this issue when the new app is accepted by @fitbit

**Comment by PatrickF1** [comment]
@mdmedley Thank you for maintaining this plugin for the sake of the community! I really appreciate it. I wouldn't have come here to bother you if there was a usable alternative (there isn't, at least not for Versa 2). Can't wait for it to be released, especially now that I can only run to exercise.

**Comment by mdmedley** [comment]
@patrickf3139 The new app was approved by @Fitbit and I just published the new build! Thank you for opening this issue. I hope you enjoy using the app! Stay safe and stay healthy!

**Comment by PatrickF1** [comment]
I saw the notification and already downloaded the app. I may be the first user of your new version, who knows? Thank you so much Marcus. Please stay healthy :)
