### ISSUE TITLE
Lower Cadence numberz

### ISSUE THREAD

**Issue by dossier23** [mdmedley/cadence-coach#4]
Hi! I would like to be able to use the cadence app for my sport - - kayaking-- which has a considerably lower rate than running.

So, the comment that I would like to make is that it is a bit laborious to get the cadence number in the app down to (say) 60 since I have to press the button 120 times.

**Comment by mdmedley** [comment]
Hi @dossier23 I'm sorry for the inconvenience, but the app is designed for running.

**Comment by mmbal21** [comment]
Hi Mdmedley/Cadence-Coach,

That is what I am looking for. I had a fitbit 1 that broke and had to get a
replacement. I chose to get the sense version. Their is not any cadence
apps compatible / available for higher then fitbit 2.

I used this app before and liked it. I would like to use it again but I am
unable to as is.

Thank you for your help
